version: "3.7"
name: async-api

services:
  etl-service_test:
    build: etl
    container_name: etl-service_test
    restart: unless-stopped
    depends_on:
      postgres_test:
        condition: service_started
      elasticsearch_test:
        condition: service_started
      redis_test:
        condition: service_started
    env_file:
      - ./etl/.env.example

  postgres_test:
    image: postgres:13
    container_name: postgres_test
    volumes:
      - ${HOME}/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./etl/.env.example
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  redis_test:
    image: redis:latest
    container_name: redis_test
    expose:
      - "6379"
    restart: unless-stopped

  elasticsearch_test:
    image: elasticsearch:8.6.2
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5