version: "3.7"
name: async-api

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      movies-api:
        condition: service_started

  etl-service:
    build: etl
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env.example

  movies-api:
    build: movies_api
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    expose:
      - "8000"
    env_file:
      - .env.example

  postgres:
    image: postgres:13
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./schema_design/scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env.example
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data
    expose:
      - "9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5